name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use system Python
        run: python3 --version

      - name: Install deps
        run: pip3 install mlflow dvc

      - name: Train
        run: python3 train.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: |
            model_info.txt
            accuracy.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download
        uses: actions/download-artifact@v4
        with:
          name: model-info

      - name: Check
        run: python3 check_threshold.py

      - name: Docker Mock
        run: echo "Building Docker image for Run ID: $(cat model_info.txt)"
