name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 train.py
      - uses: actions/upload-artifact@v4
        with:
          name: model-info
          path: |
            model_info.txt
            accuracy.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: model-info
      - run: python3 check_threshold.py
      - run: echo "Building Docker image for Run ID: $(cat model_info.txt)"
